# Basis config Datei

# Site settings
title:
email:
description:
baseurl: /lerne-jekyll  # Im Terminal den Befehl:   jekyll serve --baseurl ""     ausführen
                        # ev.   jekyll serve --watch --baseurl ""     ausführen falls nötig
exclude: ['README.md']
# Build settings
markdown: kramdown
